### PR TITLE
add AppVeyor CI

### PR DESCRIPTION
**Pull request by huangjj27**
AppVeyor can be used for Windows CI build. Now it's used test build for `ui-sys`, but can't make sure that the examples will work on Windows. More codes are needed

### CODE REVIEW

**Comment by NoraCodes** [comment]
Closing and reopening to trigger a build.

**Comment by NoraCodes** [comment]
I'm disposed to merge this as is and improve coverage over time.

**Comment by huangjj27** [comment]
I think this PR is OK for run, but I'm trying to fix the issue of failing `cargo test` at the root directory. log like:
```sh
cargo test
   Compiling ui v0.1.2 (file:///C:/Users/34937/Documents/libui-rs/ui)
error: linking with `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.10ygozpgsu0ud2lu.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.16u6js6g0l3k1ic6.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.181cuta0v63atwcm.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.1e698527iprj2v8f.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.1im38lueib99jsk0.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.1y16o1qfye96o7m0.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.23tqyymcb18u96mb.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.25rzufqyj1o51xqm.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.272abz8r2vtgyrl.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.2lyh15q6cjwzy18c.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.2uaqzytb72l21qs6.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.3ayaeypdcro9d6yk.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.3ik0x0hz6l66cx38.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.3k08uhoxpxcn9t2.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.3oqznv5oym7l3m4e.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.3rngp6bm2u2q5z0y.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.3sn52l76g15fb4ex.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.3wta9ctgdrpkmlpr.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.40xr0l91sxnt4yyo.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.45pc7c65foh9i35f.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.47n6kbsr94cs7li6.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4kcy91q98z0ihbw6.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4oc10dk278mpk1vy.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4rzh6npf1tuwcxx9.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4xq48u46a1pwiqn7.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4xt5i0ggdau05dcd.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4yekh4a49ri9ikb0.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4yh8x2b62dcih00t.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.4ypvbwho0bu5tnww.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.57k06xfugllsc526.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.5gf6du7k58s78kob.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.63mmpc50mjcb0lb.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.8xzrsc1ux72v29j.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.9elsx31vb4it187.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.y08g5q2x813c4wx.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.z9ox7biyn1otfln.rcgu.o" "/OUT:C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.exe" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.crate.allocator.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps" "/LIBPATH:C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\build\\ui-sys-8fa81161cc4bf3f7\\out\\build\\out\\Release" "/LIBPATH:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\libui-84e171efd0155c6d.rlib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\libui_sys-8421cadaf0fd1f8b.rlib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\liblibc-6d8399f81d090266.rlib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\libbitflags-04a666e761799f76.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-97796ba8f397b7ef.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-ad642e80ef7e3b4b.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-edc187001bb258e6.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-794401290a184df0.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-e25b2c1c9c6b4972.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-390b9d7b8accc3f2.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-0c13f18629eb6ca3.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-b8ecbfb3b18e83e7.rlib" "libui.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: Non-UTF-8 output: libui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.42bo7pujw320r6d.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiDrawPixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui4draw7Context10draw_image17h6345022a9d3b953eE \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.42bo7pujw320r6d.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiScalePixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui4draw7Context11scale_image17h29e17af47c048315E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiNewPixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui5image5Image3new17h375d6d0da008c948E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiImageLoadPixmap32Raw\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui5image5Image11load_pixmap17h2c24879a4dd63813E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiFreePixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN58_$LT$ui..image..Image$u20$as$u20$core..ops..drop..Drop$GT$4drop17h74b0f07c01e80e43E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiPixmapImageGetData\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui5image14get_image_data17hce5818085ea2ebf0E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nC:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\basic-17bd34e40804545f.exe : fatal error LNK1120: 6 \xb8\xf6\xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\r\n

error: aborting due to previous error

error: Could not compile `ui`.
warning: build failed, waiting for other jobs to finish...
error: linking with `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.10ygozpgsu0ud2lu.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.16u6js6g0l3k1ic6.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.181cuta0v63atwcm.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.1e698527iprj2v8f.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.1im38lueib99jsk0.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.1qjximlfqjsf20jk.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.1y16o1qfye96o7m0.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.23tqyymcb18u96mb.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.25rzufqyj1o51xqm.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.27qagd3bg3sohjvv.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.2lyh15q6cjwzy18c.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.2uaqzytb72l21qs6.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3ayaeypdcro9d6yk.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3ik0x0hz6l66cx38.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3jyx34bli2f7c57f.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3k08uhoxpxcn9t2.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3oqznv5oym7l3m4e.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3rngp6bm2u2q5z0y.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3sn52l76g15fb4ex.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.3wta9ctgdrpkmlpr.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.40xr0l91sxnt4yyo.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.45pc7c65foh9i35f.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4kcy91q98z0ihbw6.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4mogdmdhvmlumbdq.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4oc10dk278mpk1vy.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4rzh6npf1tuwcxx9.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4xq48u46a1pwiqn7.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4xt5i0ggdau05dcd.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4yekh4a49ri9ikb0.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4yh8x2b62dcih00t.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.4ypvbwho0bu5tnww.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.57k06xfugllsc526.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.5gf6du7k58s78kob.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.63mmpc50mjcb0lb.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.8xzrsc1ux72v29j.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.9elsx31vb4it187.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.y08g5q2x813c4wx.rcgu.o" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.z9ox7biyn1otfln.rcgu.o" "/OUT:C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.exe" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.crate.allocator.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps" "/LIBPATH:C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\build\\ui-sys-8fa81161cc4bf3f7\\out\\build\\out\\Release" "/LIBPATH:C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\libui-84e171efd0155c6d.rlib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\libui_sys-8421cadaf0fd1f8b.rlib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\liblibc-6d8399f81d090266.rlib" "C:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\deps\\libbitflags-04a666e761799f76.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-97796ba8f397b7ef.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-ad642e80ef7e3b4b.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-edc187001bb258e6.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-794401290a184df0.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-e25b2c1c9c6b4972.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-390b9d7b8accc3f2.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-0c13f18629eb6ca3.rlib" "C:\\Users\\34937\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-b8ecbfb3b18e83e7.rlib" "libui.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: Non-UTF-8 output: libui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.42bo7pujw320r6d.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiDrawPixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui4draw7Context10draw_image17h6345022a9d3b953eE \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.42bo7pujw320r6d.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiScalePixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui4draw7Context11scale_image17h29e17af47c048315E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiNewPixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui5image5Image3new17h375d6d0da008c948E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiImageLoadPixmap32Raw\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui5image5Image11load_pixmap17h2c24879a4dd63813E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiFreePixmapImage\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN58_$LT$ui..image..Image$u20$as$u20$core..ops..drop..Drop$GT$4drop17h74b0f07c01e80e43E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nlibui-84e171efd0155c6d.rlib(ui-84e171efd0155c6d.2d5r4lyvoeaqupbe.rcgu.o) : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 uiPixmapImageGetData\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd _ZN2ui5image14get_image_data17hce5818085ea2ebf0E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nC:\\Users\\34937\\Documents\\libui-rs\\target\\debug\\examples\\controlgallery-3fb3d3e41b6d92a1.exe : fatal error LNK1120: 6 \xb8\xf6\xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\r\n

error: aborting due to previous error

error: Could not compile `ui`.

To learn more, run the command again with --verbose.
```

**Comment by NoraCodes** [comment]
Thanks much for this!

**Pull request merged**
